name: Unity CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_VERSION: 2022.3.0f1

jobs:
  test:
    name: Run Unity EditMode Tests
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:2022.3.0f1-base-1

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Run EditMode tests
        run: |
          unity-editor \
            -batchmode \
            -nographics \
            -projectPath . \
            -runTests \
            -testPlatform EditMode \
            -testResults ./TestResults.xml \
            -quit

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: ./TestResults.xml
