name: Unity EditMode Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Run EditMode Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2022.3.14f1
          testMode: EditMode
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
