name: Unity CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    name: 🔧 Build & Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}

      - name: Create dummy test result
        run: |
          mkdir -p TestResults
          echo "<test-run result='Skipped' />" > TestResults/Results.xml

      - name: Upload dummy test result
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults/Results.xml
